name: flutter_home_work
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.1+1

  dio: ^4.0.6

  carousel_slider:
    git:
      url: https://github.com/serenader2014/flutter_carousel_slider
      ref: master


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

  json_serializable: ^6.3.1

  build_runner: ^2.2.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/space/
    - assets/sources/
    - assets/text_files/
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets\fonts\comfortaa-light.ttf
          weight: 300
        - asset: assets\fonts\comfortaa.ttf
          weight: 400
        - asset: assets\fonts\comfortaa-bold.ttf
          weight: 700
